#+TITLE: 38
你拔出武器，以为会有危险。这间黑屋子里的臭气让你窒息。你凝视着满是垃圾的房间，当你看到整个房间都被一种很像是血的液体覆盖时，你倒吸了一口凉气。在房间中央，你几乎看不出一个几乎什么都没穿的瘦骨嶙峋的人形生物。你看他的眼睛充血，他的皮肤是令人厌恶的斑驳的红色。他发出半嘶嘶半咯咯的声音，踉踉跄跄地向你走来。
你正在和这只非人类的野兽进行殊死搏斗。这个生物不会从你身边跑开，这场战斗之后，就只剩下一个了。由于他的恐怖本性，你必须先进行一次DC 10智慧豁免，否则你会被吓到1D4轮，在此期间你的攻击骰将处于劣势。
你可以与血人进行回合式战斗，或者使用冒险结束时提供的战斗地图进入战斗。在这种情况下，请进行一次DC 12智慧(洞察力)检定。如果你成功了，血人会从门附近开始，你可以在地图上选择你的起始位置。如果你失败了，你就从靠近门口的地方开始。
如果你的角色卡上标有“黑暗”状态，那就麻烦大了。血人能在黑暗中看见东西，到你的攻击骰时你处于劣势，除非你有法术或者技能能够抵消此劣势。
血人的策略是先用爪子伤害目标，然后用他的渗血能力抓住他们，开始溶解和吸收受害者。

** 怪物信息
怪物名称：血人
中型不死生物
阵营：中立邪恶
装备等级（AC）：10
速度：30尺
HP：26（3d10+9）

*** 属性
| 力量     | 敏捷 | 体质     | 智慧    | 感知    | 魅力    |
|---------+-----+---------+--------+--------+--------|
| 15 (+2) |  11 | 16 (+3) | 5 (-3) | 6 (-2) | 5 (-3) |

*** 特性
死亡豁免：DC 感知属性值，无调整值
免疫中毒、腐蚀伤害
免疫中毒、衰竭状态
黑暗视觉60
被动感知10
语言：能听懂日常说的所有语言，但不会说
挑战（1/2）：100经验值

*** 攻击方式
挥爪攻击：近战攻击，命中骰+3，范围5尺，目标个数：1，伤害：4（1d6+1）划伤
渗血：一旦目标受伤，血人就会视图将其带有腐蚀性的血液渗透到目标体内。近战攻击，命中骰+4，范围5尺，目标个数：1，伤害：9（2d6+2）腐蚀，目标必须立即进行一次DC 10的体质豁免，或者直接进入筋疲力尽状态。

** 选择
- 如果你杀死了血人，请执行如下代码
  #+begin_src emacs-lisp :results none
    (goto-paragraph "48")
  #+end_src

- 如果你被血人杀死，那么你的冒险到此结束

** 结局
也许比你更坚强的英雄会回到城堡去打败这个可怕的生物。
